anul2/daw/OurReddit/OurReddit/Controllers/CategoryController.cs
using Microsoft.AspNet.Identity;
using OurReddit.ActionFilters;
using OurReddit.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Linq.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Generator;

namespace OurReddit.Controllers
{
    public class CategoryController : Controller
    {
        private readonly Models.ApplicationDbContext db = new Models.ApplicationDbContext();

        private static int PER_PAGE = 5;
        
        private static List<SelectListItem> SortingMethods = new List<SelectListItem> 
        {
            new SelectListItem { Text = "Alfabetic crescator", Value = "1"},
            new SelectListItem { Text = "Alfabetic descrescator", Value = "2"},
            new SelectListItem { Text = "Cele mai recente primele", Value = "3"},
            new SelectListItem { Text = "Cele mai vechi primele", Value = "4"},
        };
            
        [HttpGet]
        [AlertFilter]
        //oricine poate vedea categoriile
        public ActionResult Index()
        {
            SetAccessRights();
            
            // cautare
            string search = "";
            if (Request.Params.Get("search") != null)
            {
                search = Request.Params.Get("search").Trim();
            }

            var categories = from category in db.Categories
                             where category.Name.Contains(search)
                             orderby category.Name
                             select category;

            int currentPage = Convert.ToInt32(Request.Params.Get("pageNumber"));
            int offset = currentPage * PER_PAGE;
            int totalCategories = categories.Count();

            // sortare
            int sort = 0;
            if (Request.Params.Get("sort") != null && Request.Params.Get("sort") != "")
            {
                sort = Convert.ToInt32(Request.Params.Get("sort"));
            }

            if (sort == 1)
            {
                categories = categories.OrderBy(c => c.Name);
            } 
            else if (sort == 2)
            {
                categories = categories.OrderByDescending(c => c.Name);
            }
            else if (sort == 3)
            {
                categories = categories.OrderByDescending(c => c.DateCreated);
            }
            else if (sort == 4)
            {
                categories = categories.OrderBy(c => c.DateCreated);
            }

            categories = (IOrderedQueryable<Category>)categories.Skip(offset).Take(PER_PAGE);

            ViewBag.Categories = categories;
            ViewBag.perPage = PER_PAGE;
            ViewBag.total = totalCategories;
            ViewBag.currentPage = currentPage;
            ViewBag.lastPage = totalCategories / PER_PAGE + (totalCategories % PER_PAGE != 0 ? 1 : 0);
            ViewBag.SearchString = search;
            ViewBag.SortingMethods = SortingMethods;
            ViewBag.SortId = sort;

            return View();
        }

        [HttpGet]
        [AlertFilter]
        public ActionResult Show(int id)
        {
            SetAccessRights();

            string search = "";
            if (Request.Params.Get("search") != null)
            {
                search = Request.Params.Get("search").Trim();
            }

            Category category = db.Categories.Find(id);

            List<int> subjectIds = db.Subjects
                .Where(s => s.Title.Contains(search) || s.Description.Contains(search))
                .Select(s => s.Id).ToList();

            List<int> messageIds = db.Messages
                .Where(m => m.Content.Contains(search))
                .Select(m => m.SubjectId).ToList();

            List<int> mergedIds = subjectIds.Union(messageIds).ToList();

            int currentPage = Convert.ToInt32(Request.Params.Get("pageNumber"));
            int offset = currentPage * PER_PAGE;
            category.Subjects = category.Subjects.Where(s => mergedIds.Contains(s.Id)).ToList();
            int totalSubjects = category.Subjects.Count();

            // sortare
            int sort = 0;
            if (Request.Params.Get("sort") != null && Request.Params.Get("sort") != "")
            {
                sort = Convert.ToInt32(Request.Params.Get("sort"));
            }

            if (sort == 1)
            {
                category.Subjects = category.Subjects.OrderBy(s => s.Title).ToList();
            }
            else if (sort == 2)
            {
                category.Subjects = category.Subjects.OrderByDescending(s => s.Title).ToList();
            }
            else if (sort == 3)
            {
                category.Subjects = category.Subjects.OrderByDescending(s => s.DateCreated).ToList();
            }
            else if (sort == 4)
            {
                category.Subjects = category.Subjects.OrderBy(s => s.DateCreated).ToList();
            }

            category.Subjects = category.Subjects.Skip(offset).Take(PER_PAGE).ToList();

            ViewBag.Category = category;
            ViewBag.perPage = PER_PAGE;
            ViewBag.total = totalSubjects;
            ViewBag.currentPage = currentPage;
            ViewBag.lastPage = totalSubjects / PER_PAGE + (totalSubjects % PER_PAGE != 0 ? 1 : 0);
            ViewBag.SearchString = search;
            ViewBag.SortingMethods = SortingMethods;
            ViewBag.SortId = sort;

            return View();
        }
        
        [HttpGet]
        [AlertFilter]
        [Authorize(Roles = "Admin")]
        public ActionResult New()
        {
            SetAccessRights();
            return View();
        }

        [HttpPost]
        // doar admin poate crea categorie noua
        [Authorize(Roles="Admin")]
        public ActionResult New(Category category)
        {
            try
            {
                db.Categories.Add(category);
                db.SaveChanges();
                TempData["Alert"] = "Ai creat o categorie noua: " + category.Name.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["Alert"] = "Eroare la crearea categoriei";
                return View();
            }
        }
        
        [HttpGet]
        [AlertFilter]
        // doar admin poate modifica categoriile
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            SetAccessRights();
            Category category = db.Categories.Find(id);
            ViewBag.Category = category;
            return View(category);
        }

        [HttpPut]
        [Authorize(Roles = "Admin")]
        // doar admin poate modifica categoriile
        public ActionResult Edit(int id, Category requestCategory)
        {
            try
            {
                Category category = db.Categories.Find(id);
                if (TryUpdateModel(category))
                {
                    category.Name = requestCategory.Name;
                    db.SaveChanges();
                    TempData["Alert"] = "Ai editat categoria: " + category.Name.ToString();
                }
                else
                {
                    TempData["Alert"] = "Eroare la editarea categoriei";
                    return View(category);
                }
                return RedirectToAction("Index");
            } 
            catch (Exception e)
            {
                TempData["Alert"] = "Eroare la editarea categoriei";
                return View();
            }
        }

        [HttpDelete]
        // doar admin poate sterge categoriile
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            TempData["Alert"] = "Ai sters categoria: " + category.Name.ToString();
            return RedirectToAction("Index");
        }

        [NonAction]
        private void SetAccessRights()
        {
            ViewBag.isAdmin = User.IsInRole("Admin");
            ViewBag.isModerator = User.IsInRole("Moderator");
            ViewBag.currentUserId = User.Identity.GetUserId();
        }
    }
}

anul2/daw/OurReddit/OurReddit/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using OurReddit.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OurReddit.Controllers
{
    public class UsersController : Controller
    {
        private readonly Models.ApplicationDbContext db = new Models.ApplicationDbContext();

        // GET: Users
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;

            string userId = User.Identity.GetUserId();
            ViewBag.UsersList = users.Where(u => u.Id != userId).ToList();
            return View();
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public ActionResult Show(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            ViewBag.CurrentUser = User.Identity.GetUserId();
            string currentRole = user.Roles.FirstOrDefault().RoleId;

            var userRoleName = (from role in db.Roles where role.Id == currentRole select role.Name).First();
            ViewBag.roleName = userRoleName;

            return View(user);
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public ActionResult Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            if (user == null)
            {
                return Redirect("/Category/Index");
            }
            user.AllRoles = GetAllRoles();
            var userRole = user.Roles.FirstOrDefault();
            ViewBag.userRole = userRole.RoleId;
            return View(user);
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        [HttpPut]
        public ActionResult Edit(string id, ApplicationUser newData)
        {
            ApplicationUser user = db.Users.Find(id);
            user.AllRoles = GetAllRoles();
            var userRole = user.Roles.FirstOrDefault();
            ViewBag.userRole = userRole.RoleId;

            try
            {
                ApplicationDbContext context = new ApplicationDbContext();
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                if (TryUpdateModel(user))
                {
                    user.UserName = newData.UserName;
                    user.Email = newData.Email;
                    user.PhoneNumber = newData.PhoneNumber;

                    var selectedRole = db.Roles.Find(HttpContext.Request.Params.Get("newRole"));
                    if (selectedRole != null)
                    {
                        var roles = from role in db.Roles select role;

                        foreach (var role in roles)
                        {
                            UserManager.RemoveFromRole(id, role.Name);
                        }

                        UserManager.AddToRole(id, selectedRole.Name);
                    }
                  
                    db.SaveChanges();
                }
                return RedirectToAction("Show/" + user.Id);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                newData.Id = id;
                return View(newData);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpDelete]
        public ActionResult Delete(string id)
        {
            ApplicationDbContext context = new ApplicationDbContext();

            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

            var user = UserManager.Users.FirstOrDefault(u => u.Id == id);

            var subjects = db.Subjects.Where(a => a.UserId == id);
            foreach (var subject in subjects)
            {
                db.Subjects.Remove(subject);

            }

            var messages = db.Messages.Where(comm => comm.UserId == id);
            foreach (var message in messages)
            {
                db.Messages.Remove(message);
            }

            db.SaveChanges();
            UserManager.Delete(user);
            return RedirectToAction("Index");
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();

            var roles = from role in db.Roles select role;
            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });
            }
            return selectList;
        }
    }
}

anul2/daw/OurReddit/OurReddit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=East+Sea+Dokdo&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OurReddit", "Index", "Category", new { area = "" }, new { @class = "navbar-brand logo our-logo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            @Html.ActionLink("Administrare utilizatori", "Index", "Users", new { area = "" }, new { @class = "nav-item" })
                        </li>
                    }
                </ul>
                    @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div style="font-size: 2.5rem!important; font-weight: 500!important;" class="footer-content our-logo">
                <p>OurReddit &copy; @DateTime.Now.Year - Nix & Stef 🍉</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @Scripts.Render("~/bundles/customScripts")

    <script defer>
        showPopup("@ViewBag.alert");
    </script>

</body>
</html>

anul2/daw/OurReddit/OurReddit/Views/Shared/_SearchSort.cshtml
<div class="container">
    <div class="row">
        <form class="col-lg-6" method="GET">
            <div class="row">
                <input style="margin-right:10px;" class="col-md-4 form-control form-controlborderless" type="text" name="search"
                       value="@ViewBag.SearchString"
                       placeholder="Cauta @ViewBag.What">
                <button class="col-md-2 btn btn-success" type="submit">
                    Cauta
                </button>
            </div>
        </form>

        @using (Html.BeginForm((string) ViewBag.Action, (string) ViewBag.Route, FormMethod.Get, new { @class = "col-lg-6" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                @Html.DropDownList("sort", @ViewBag.SortingMethods as List<SelectListItem>,
                    "Sorteaza " + (string)ViewBag.What, new
                         {
                        @style = "margin-right:10px;",
                        @class = "col-md-4 form-control form-controlborderless"
                    })

                @Html.Hidden("search", (string)@ViewBag.SearchString)

                @Html.Hidden("pageNumber", (string)@ViewBag.currentPage.ToString())

                <button class="col-md-2 btn btn-success" type="submit">
                    Sorteaza
                </button>
            </div>
        }
    </div>
</div>
<br />